[package]
name = "wreq_cli"
version = "0.2.0"
authors = ["sergey gapchenko <gapchenko42@gmail.com>"]
edition = "2024"
publish = false

[dependencies]
clap = { version = "4.6.2", features = ["derive"] }
tokio = { version = "1.50.0", features = ["rt", "rt-multi-thread"] }
wreq = { version = "5.3.0", features = ["gzip", "stream", "cookies", "socks"] }
wreq-util = "2.2.6"
anyhow = "1.0.100"
#bincode = "=1.3.3"
base64 = "=0.22.1"

[build-dependencies]
thunk-rs = { version = "0.3.5", features = ["xp"] } #"subsystem_windows", , "vc_ltl_only"
