[package]
name = "rt_ocr"
version = "1.0.0"
authors = ["sergey gapchenko <gapchenko42@gmail.com>"]
edition = "2024"
publish = false

[dependencies]
ocr-rs = { version = "2.3.2"}
image = "0.25"

[build-dependencies]
thunk-rs = { version = "0.3.5", features = ["xp"] } #"subsystem_windows", , "vc_ltl_only"

[profile.release]
strip = true
#codegen-units = 1
#panic = "abort"
lto = true
opt-level = "z"
