name: Release Windows x86

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build Windows
    runs-on: windows-2022
    steps:
      - name: Configure Git Line Endings
        run: |
          git config --system core.autocrlf false
          git config --system core.eol lf

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable-msvc
          target: i686-pc-windows-msvc

      - name: Cache cargo
        uses: swatinem/rust-cache@v2
        with:
          workspaces: |
            rt_ocr -> rt_ocr/target
            wreq_cli -> wreq_cli/target

      - name: Install dependencies on Windows
        run: |
          choco install cmake -y
          choco install strawberryperl -y
          choco install pkgconfiglite -y
          choco install llvm -y
          choco install nasm -y
        shell: cmd

      - name: Build rt_ocr on Windows x86
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
        run: cargo build --release --locked --manifest-path rt_ocr/Cargo.toml --target i686-pc-windows-msvc

      - name: Build rt_ocr on Windows x64
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
        run: cargo build --release --locked --manifest-path rt_ocr/Cargo.toml --target x86_64-pc-windows-msvc

      - name: Build wreq_cli on Windows x86
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
        run: cargo build --release --locked --manifest-path wreq_cli/Cargo.toml --target i686-pc-windows-msvc

      - name: Build wreq_cli on Windows x64
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
        run: cargo build --release --locked --manifest-path wreq_cli/Cargo.toml --target x86_64-pc-windows-msvc

      - name: Rename x64 binaries
        shell: pwsh
        run: |
          Copy-Item rt_ocr/target/x86_64-pc-windows-msvc/release/rt_ocr.exe rt_ocr/target/x86_64-pc-windows-msvc/release/rt_ocr_x64.exe
          Copy-Item wreq_cli/target/x86_64-pc-windows-msvc/release/wreq_cli.exe wreq_cli/target/x86_64-pc-windows-msvc/release/wreq_cli_x64.exe

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            rt_ocr/target/i686-pc-windows-msvc/release/rt_ocr.exe
            wreq_cli/target/i686-pc-windows-msvc/release/wreq_cli.exe
            rt_ocr/target/x86_64-pc-windows-msvc/release/rt_ocr_x64.exe
            wreq_cli/target/x86_64-pc-windows-msvc/release/wreq_cli_x64.exe
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          